services:
  mongodb:
    image: mongo:7
    container_name: carrent-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: carrent
      MONGO_INITDB_ROOT_PASSWORD: carrent1234
      MONGO_INITDB_DATABASE: carrent
    volumes:
      - carrent_mongo_data:/data/db

volumes:
  carrent_mongo_data:
