import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

import mongoose from 'mongoose'
import { Vehicle } from '../src/lib/models/Vehicle'

const vehicles = [
  {
    licensePlate: 'กข-1001-กทม',
    brand: 'Toyota',
    model: 'Camry',
    year: 2024,
    seats: 5,
    color: 'Silver',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1200,
    pricePerWeek: 7500,
    pricePerMonth: 25000,
    images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80'],
    features: ['Bluetooth', 'กล้องถอยหลัง', 'เบาะหนัง', 'ระบบนำทาง GPS'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Toyota Camry 2024 สีเงิน รถสปอร์ตหรูหรา สะดวกสบาย เหมาะสำหรับการเดินทางธุรกิจและท่องเที่ยว',
  },
  {
    licensePlate: 'กข-1002-กทม',
    brand: 'Honda',
    model: 'Accord',
    year: 2024,
    seats: 5,
    color: 'Black',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1100,
    pricePerWeek: 7000,
    pricePerMonth: 23000,
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80'],
    features: ['Apple CarPlay', 'ระบบเบรกฉุกเฉิน', 'เบาะปรับไฟฟ้า', 'หลังคา Sunroof'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Honda Accord 2024 สีดำ รถยนต์หรูหราระดับพรีเมียม พร้อมระบบความปลอดภัยล้ำสมัย',
  },
  {
    licensePlate: 'กข-1003-ชม',
    brand: 'Toyota',
    model: 'Fortuner',
    year: 2024,
    seats: 7,
    color: 'White',
    fuelType: 'diesel' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1800,
    pricePerWeek: 11000,
    pricePerMonth: 38000,
    images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80'],
    features: ['4WD', 'ระบบนำทาง GPS', 'กล้อง 360°', 'เบาะแถว 3'],
    status: 'available' as const,
    location: 'เชียงใหม่',
    isActive: true,
    description: 'Toyota Fortuner 2024 สีขาว SUV ขนาดใหญ่ ขับเคลื่อน 4 ล้อ เหมาะสำหรับผจญภัยทุกเส้นทาง',
  },
  {
    licensePlate: 'กข-1004-กทม',
    brand: 'Honda',
    model: 'CR-V',
    year: 2024,
    seats: 5,
    color: 'Gray',
    fuelType: 'hybrid' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1600,
    pricePerWeek: 10000,
    pricePerMonth: 34000,
    images: ['https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80'],
    features: ['Hybrid', 'Honda Sensing', 'Wi-Fi Hotspot', 'เบาะหนัง'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Honda CR-V 2024 Hybrid สีเทา SUV ไฮบริดประหยัดพลังงาน พร้อมเทคโนโลยีความปลอดภัย Honda Sensing',
  },
  {
    licensePlate: 'กข-1005-ภก',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2023,
    seats: 5,
    color: 'White',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 900,
    pricePerWeek: 5800,
    pricePerMonth: 19000,
    images: ['https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80'],
    features: ['Toyota Safety Sense', 'Apple CarPlay', 'กล้องถอยหลัง'],
    status: 'available' as const,
    location: 'ภูเก็ต',
    isActive: true,
    description: 'Toyota Corolla 2023 สีขาว รถยนต์นั่งยอดนิยม ประหยัดน้ำมัน เหมาะสำหรับการเดินทางในเมือง',
  },
  {
    licensePlate: 'กข-1006-กทม',
    brand: 'Mazda',
    model: 'Mazda3',
    year: 2024,
    seats: 5,
    color: 'Red',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1000,
    pricePerWeek: 6500,
    pricePerMonth: 22000,
    images: ['https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=800&q=80'],
    features: ['Mazda i-Activsense', 'Head-Up Display', 'เบาะหนัง Nappa'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Mazda3 2024 สีแดง ดีไซน์สปอร์ตสวยงาม พร้อมระบบขับขี่อัจฉริยะ Mazda i-Activsense',
  },
  {
    licensePlate: 'กข-1007-กทม',
    brand: 'Honda',
    model: 'City',
    year: 2023,
    seats: 5,
    color: 'Blue',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 800,
    pricePerWeek: 5000,
    pricePerMonth: 17000,
    images: ['https://images.unsplash.com/photo-1603386329225-868f9b1ee6c9?w=800&q=80'],
    features: ['Honda Sensing', 'Apple CarPlay', 'กล้องถอยหลัง'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Honda City 2023 สีน้ำเงิน รถยนต์นั่งขนาดกลาง ประหยัดพลังงาน ราคาคุ้มค่า',
  },
  {
    licensePlate: 'กข-1008-ชม',
    brand: 'Toyota',
    model: 'Hilux Revo',
    year: 2024,
    seats: 5,
    color: 'White',
    fuelType: 'diesel' as const,
    transmission: 'manual' as const,
    pricePerDay: 1400,
    pricePerWeek: 9000,
    pricePerMonth: 30000,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],
    features: ['4WD', 'กระบะบรรทุก', 'ระบบนำทาง GPS', 'ล้ออัลลอย'],
    status: 'available' as const,
    location: 'เชียงใหม่',
    isActive: true,
    description: 'Toyota Hilux Revo 2024 สีขาว กระบะแข็งแกร่ง ขับเคลื่อน 4 ล้อ เหมาะสำหรับงานหนักและออฟโรด',
  },
  {
    licensePlate: 'กข-1009-กทม',
    brand: 'Ford',
    model: 'Ranger',
    year: 2024,
    seats: 5,
    color: 'Black',
    fuelType: 'diesel' as const,
    transmission: 'automatic' as const,
    pricePerDay: 1500,
    pricePerWeek: 9500,
    pricePerMonth: 32000,
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80'],
    features: ['4WD', 'Ford Co-Pilot360', 'กล้อง 360°', 'ระบบนำทาง GPS'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Ford Ranger 2024 สีดำ กระบะพรีเมียม สมรรถนะสูง พร้อมระบบความปลอดภัย Ford Co-Pilot360',
  },
  {
    licensePlate: 'กข-1010-กทม',
    brand: 'Toyota',
    model: 'Alphard',
    year: 2024,
    seats: 7,
    color: 'Silver',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 3500,
    pricePerWeek: 22000,
    pricePerMonth: 75000,
    images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80'],
    features: ['เบาะ Captain แถว 2', 'ระบบนำทาง GPS', 'จอหลัง', 'ม่านไฟฟ้า'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Toyota Alphard 2024 สีเงิน รถตู้หรูระดับ VIP เบาะ Captain chair พร้อมสิ่งอำนวยความสะดวกสุดหรู',
  },
  {
    licensePlate: 'กข-1011-กทม',
    brand: 'Honda',
    model: 'Odyssey',
    year: 2024,
    seats: 7,
    color: 'White',
    fuelType: 'gasoline' as const,
    transmission: 'automatic' as const,
    pricePerDay: 2800,
    pricePerWeek: 17500,
    pricePerMonth: 60000,
    images: ['https://images.unsplash.com/photo-1543465077-db45d34b88a5?w=800&q=80'],
    features: ['Magic Seat', 'Apple CarPlay', 'กล้อง 360°', 'Wi-Fi Hotspot'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Honda Odyssey 2024 สีขาว รถตู้ครอบครัว Magic Seat ปรับเปลี่ยนได้หลากหลาย เหมาะสำหรับครอบครัว',
  },
  {
    licensePlate: 'กข-1012-กทม',
    brand: 'Toyota',
    model: 'GR86',
    year: 2024,
    seats: 4,
    color: 'Yellow',
    fuelType: 'gasoline' as const,
    transmission: 'manual' as const,
    pricePerDay: 2200,
    pricePerWeek: 14000,
    pricePerMonth: 48000,
    images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80'],
    features: ['Sport Mode', 'Brembo Brakes', 'ระบบกันสั่น', 'ล้ออัลลอย BBS'],
    status: 'available' as const,
    location: 'กรุงเทพฯ',
    isActive: true,
    description: 'Toyota GR86 2024 สีเหลือง รถสปอร์ตสมรรถนะสูง ดีไซน์โฉบเฉี่ยว เหมาะสำหรับผู้ที่ชื่นชอบความเร็ว',
  },
]

async function seed() {
  const uri = process.env.MONGODB_URI
  if (!uri) {
    console.error('MONGODB_URI not found in .env.local')
    process.exit(1)
  }

  await mongoose.connect(uri)
  console.log('Connected to MongoDB')

  await Vehicle.deleteMany({})
  console.log('Cleared existing vehicles')

  await Vehicle.insertMany(vehicles)
  console.log(`✅ Seeded ${vehicles.length} vehicles successfully`)

  await mongoose.disconnect()
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
